# Matugen Hyprland Colors

$background = rgb(0e1513)

$error = rgb(ffb4ab)

$error_container = rgb(93000a)

$inverse_on_surface = rgb(2b3230)

$inverse_primary = rgb(056b5b)

$inverse_surface = rgb(dee4e0)

$on_background = rgb(dee4e0)

$on_error = rgb(690005)

$on_error_container = rgb(ffdad6)

$on_primary = rgb(00382f)

$on_primary_container = rgb(a0f2de)

$on_primary_fixed = rgb(00201a)

$on_primary_fixed_variant = rgb(005144)

$on_secondary = rgb(1d352f)

$on_secondary_container = rgb(cde8e0)

$on_secondary_fixed = rgb(06201a)

$on_secondary_fixed_variant = rgb(334b45)

$on_surface = rgb(dee4e0)

$on_surface_variant = rgb(bec9c5)

$on_tertiary = rgb(113348)

$on_tertiary_container = rgb(c8e6ff)

$on_tertiary_fixed = rgb(001e2f)

$on_tertiary_fixed_variant = rgb(2b4a5f)

$outline = rgb(89938f)

$outline_variant = rgb(3f4946)

$primary = rgb(84d6c2)

$primary_container = rgb(005144)

$primary_fixed = rgb(a0f2de)

$primary_fixed_dim = rgb(84d6c2)

$scrim = rgb(000000)

$secondary = rgb(b1ccc4)

$secondary_container = rgb(334b45)

$secondary_fixed = rgb(cde8e0)

$secondary_fixed_dim = rgb(b1ccc4)

$shadow = rgb(000000)

$source_color = rgb(33baa2)

$surface = rgb(0e1513)

$surface_bright = rgb(343b38)

$surface_container = rgb(1b211f)

$surface_container_high = rgb(252b29)

$surface_container_highest = rgb(303634)

$surface_container_low = rgb(171d1b)

$surface_container_lowest = rgb(090f0e)

$surface_dim = rgb(0e1513)

$surface_tint = rgb(84d6c2)

$surface_variant = rgb(3f4946)

$tertiary = rgb(abcae4)

$tertiary_container = rgb(2b4a5f)

$tertiary_fixed = rgb(c8e6ff)

$tertiary_fixed_dim = rgb(abcae4)

